spring:
  application:
    name: shabao-upms
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/shabao_cloud?useUnicode=true&characterEncoding=utf8
    username: master
    password: 19911105man
    driver-class-name: com.mysql.jdbc.Driver
    
server:
  port: 9011
  
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ #非认证模式
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #服务端管理界面显示ip地址
    
#mybatis
mybatis:
  #实体类包名，设置后可以用类名代替全路径名称
  type-aliases-package: com.xiaoshabao.upms.entity
  #设置mapper存放位置
  mapper-locations: classpath:mapper/**.xml
  #开启驼峰命名规范
  configuration:
    mapUnderscoreToCamelCase: true