server:
  port: 9010

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ #非认证模式
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #服务端管理界面显示ip地址

spring:
  application:
    name: shabao-auth
  profiles:
    active: "@profiles.active@"
  #开启当前安全认证后，需要密码才能链接配置中心  
  security:
    basic:
      enabled: true
    user:
      name: user
      password: 123
  freemarker:
    request-context-attribute: request
  datasource:
    url: jdbc:mysql://47.75.206.89:3306/shabao_blog_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: master
    password: 19911105man
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    port: 6379
    host: 47.75.206.89
    password: 19911105man
    pool:
      max-active: 20
custom:
  oauth2:
    client:
      - {clientId: shabao, clientSecret: 123456, grantType: password}
      - {clientId: shabao2, clientSecret: 123456, grantType: password}
#management:
#  security:
#    enabled: false
#  endpoints.web.exposure.include: '*'

logging:
  level:
    org.springframework.cloud.gateway: debug
  path: /app/data/logs
    
