server:
  port: 8090

spring:
  application:
    name: shabao-config
  profiles:
    active: native 
  cloud:
    config:
      #设置文件读取目录,默认会读取classpath下的文件,自定义读取config下的
      server.native.searchLocations: [classpath:/config/dev, file:./config/dev, classpath:/config/prd, file:./config/prd]
      discovery.enabled: true
      fail-fast: true
      retry:
        max-attempts: 3 #重试次数
#  security:
#    basic:
#      enabled: true
#    user:
#      name: user
#      password: 123
  freemarker:
    request-context-attribute: request
    
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ #非认证模式
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #服务端管理界面显示ip地址

#management:
#  security:
#    enabled: false
#  endpoints.web.exposure.include: '*'
    
