server:
  port: 9010

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ #非认证模式
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #服务端管理界面显示ip地址

spring:
  application:
    name: shabao-auth
  profiles:
    active: @profiles.active@
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: shabao-config
      #获取不到配置，直接结束程序
      fail-fast: true
      retry:
        max-attempts: 3 #重试次数
  config:
    #直接访问可以设置地址：http://localhost:8090
    import: configserver:http://shabao-config

