spring:
  application:
    name: shabao-center

server:
  port: 8761 #启动端口

eureka:
  instance:
    hostname: localhost #主机名，不启用会报401
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
  service-url:
#    defaultZone: http://localhost:${server.port}/eureka/ #非认证模式，无需密码进入管理界面
    defaultZone: http://user:123@localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0 # 设置同步为空时的等待时间。默认 5 * MINUTES 

#开启当前安全认证后，需要密码才能进入  eureka管理界面    
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123
      