spring:
  application:
    name: shabao-gate
  freemarker:
    request-context-attribute: request

server:
  port: 9001
  
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ #非认证模式
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #服务端管理界面显示ip地址
    
#配置路由
zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: shabao-admin
    upms:
      path: /upms/**
      serviceId: shabao-upms
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: shabao-auth
      
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9001/uaa/oauth/token
      user-authorization-uri: http://localhost:9001/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:9001/uaa/user
      prefer-token-info: false
